<script setup lang="ts">
/**
 * Renders a content string, or a pending marker if it is a placeholder.
 *
 * The value is Markdown written in the admin panel. `renderRichText` escapes it
 * before putting back the small set of tags it supports, so what is rendered
 * here can only ever be markup this codebase generated — never markup an author
 * typed. See utils/richtext.ts.
 */
const props = defineProps<{ value?: string | null; file?: string; class?: string }>()

const html = computed(() => renderRichText(props.value))
</script>

<template>
  <!-- eslint-disable vue/no-v-html -- renderRichText escapes the author's text
       before emitting any tag, so this can only ever be markup generated by
       utils/richtext.ts. -->
  <div
    v-if="hasContent(props.value)"
    :class="['prose-rich leading-relaxed text-fg-muted', props.class]"
    v-html="html"
  />
  <!-- eslint-enable vue/no-v-html -->
  <UiPending v-else-if="isPending(props.value)" :value="props.value!" :file="props.file" />
</template>
