-- Seed content, generated by frontend/scripts/export-seed.mjs — do not edit by hand.
-- Regenerate with: cd frontend && node scripts/export-seed.mjs
--
-- Every INSERT is idempotent, so applying this twice is harmless and it can
-- be re-run against a database that already holds some of these rows.

SET @now = UTC_TIMESTAMP();

-- ── Projects ───────────────────────────────────────────────────────────────

INSERT INTO projects
    (slug, title, category, description, summary, image, image_alt, year,
     live_url, github_url, featured, published, sort_order, created_at, updated_at)
VALUES
    ('bubble-white', 'Bubble White', 'E-commerce / Web Application', 'A Cambodia-focused clothing e-commerce platform covering product discovery, shopping workflows, customer accounts, orders, promotions, image management, and payment integration.', 'A Cambodia-focused clothing e-commerce platform. The system covers the full commercial path — browsing and product discovery, cart and checkout workflows, customer accounts, order handling, promotions, product image management, and payment integration — together with the administration needed to operate it day to day.',
     NULL, NULL, NULL, NULL, NULL,
     1, 1, 1, @now, @now)
ON DUPLICATE KEY UPDATE slug = slug;
SET @pid = (SELECT id FROM projects WHERE slug = 'bubble-white');
INSERT INTO project_technologies (project_id, name, sort_order) VALUES (@pid, 'Nuxt', 0) ON DUPLICATE KEY UPDATE sort_order = VALUES(sort_order);
INSERT INTO project_technologies (project_id, name, sort_order) VALUES (@pid, 'Vue', 1) ON DUPLICATE KEY UPDATE sort_order = VALUES(sort_order);
INSERT INTO project_technologies (project_id, name, sort_order) VALUES (@pid, 'Tailwind CSS', 2) ON DUPLICATE KEY UPDATE sort_order = VALUES(sort_order);
INSERT INTO project_technologies (project_id, name, sort_order) VALUES (@pid, 'MySQL', 3) ON DUPLICATE KEY UPDATE sort_order = VALUES(sort_order);
INSERT INTO project_technologies (project_id, name, sort_order) VALUES (@pid, 'Cloudflare', 4) ON DUPLICATE KEY UPDATE sort_order = VALUES(sort_order);
INSERT INTO project_technologies (project_id, name, sort_order) VALUES (@pid, 'Payment APIs', 5) ON DUPLICATE KEY UPDATE sort_order = VALUES(sort_order);

INSERT INTO case_studies
    (project_id, overview, context, problem, role, approach, architecture,
     database_notes, api_notes, security, deployment, outcome,
     features, challenges, decisions, updated_at)
VALUES
    (@pid, 'An online clothing store for the Cambodian market, built as a complete commerce system rather than a catalogue site: customers browse and buy, and the business operates orders, stock imagery, and promotions from the same application.', 'TODO: who the store serves, how they sold before this existed, and what scale it operates at.', 'TODO: the specific problem the platform was built to solve.', 'TODO: which parts you owned — data model, API, storefront, admin, deployment.',
     'TODO: how you sequenced the build and why.', 'TODO: request path, rendering strategy, and where each responsibility lives.', 'TODO: core tables, key relationships, and the indexes that matter.', 'TODO: endpoint surface, auth model, and validation strategy.',
     'TODO: authentication, authorization, payment handling, and hardening.', 'TODO: hosting, TLS, Cloudflare configuration, and release process.', 'TODO: what the platform does for the business now. No invented metrics.',
     '["Product discovery and browsing","Shopping and checkout workflow","Customer accounts","Order management","Promotions","Product image management","Payment integration"]', '["TODO: a real constraint you hit, and how you resolved it."]', '[{"decision":"TODO: a technical decision you made","rationale":"TODO: why, and what you traded away"}]', @now)
ON DUPLICATE KEY UPDATE project_id = project_id;

INSERT INTO projects
    (slug, title, category, description, summary, image, image_alt, year,
     live_url, github_url, featured, published, sort_order, created_at, updated_at)
VALUES
    ('coffee-app', 'Coffee App', 'Mobile / Business Application', 'TODO: one sentence describing what this application does, in business terms.', NULL,
     NULL, NULL, NULL, NULL, NULL,
     1, 1, 2, @now, @now)
ON DUPLICATE KEY UPDATE slug = slug;
SET @pid = (SELECT id FROM projects WHERE slug = 'coffee-app');
INSERT INTO project_technologies (project_id, name, sort_order) VALUES (@pid, 'Flutter', 0) ON DUPLICATE KEY UPDATE sort_order = VALUES(sort_order);

INSERT INTO case_studies
    (project_id, overview, context, problem, role, approach, architecture,
     database_notes, api_notes, security, deployment, outcome,
     features, challenges, decisions, updated_at)
VALUES
    (@pid, 'TODO: what the app is and who uses it.', NULL, NULL, 'TODO: which parts you built.',
     NULL, NULL, NULL, NULL,
     NULL, NULL, NULL,
     NULL, NULL, NULL, @now)
ON DUPLICATE KEY UPDATE project_id = project_id;

INSERT INTO projects
    (slug, title, category, description, summary, image, image_alt, year,
     live_url, github_url, featured, published, sort_order, created_at, updated_at)
VALUES
    ('check-in-app', 'Check-in App', 'Application', 'TODO: one sentence describing what gets checked in, by whom, and why.', NULL,
     NULL, NULL, NULL, NULL, NULL,
     1, 1, 3, @now, @now)
ON DUPLICATE KEY UPDATE slug = slug;
SET @pid = (SELECT id FROM projects WHERE slug = 'check-in-app');
INSERT INTO project_technologies (project_id, name, sort_order) VALUES (@pid, 'Flutter', 0) ON DUPLICATE KEY UPDATE sort_order = VALUES(sort_order);

INSERT INTO case_studies
    (project_id, overview, context, problem, role, approach, architecture,
     database_notes, api_notes, security, deployment, outcome,
     features, challenges, decisions, updated_at)
VALUES
    (@pid, 'TODO: what the app is and who uses it.', NULL, NULL, 'TODO: which parts you built.',
     NULL, NULL, NULL, NULL,
     NULL, NULL, NULL,
     NULL, NULL, NULL, @now)
ON DUPLICATE KEY UPDATE project_id = project_id;

INSERT INTO projects
    (slug, title, category, description, summary, image, image_alt, year,
     live_url, github_url, featured, published, sort_order, created_at, updated_at)
VALUES
    ('buffet-system', 'Buffet System', 'Restaurant / POS System', 'TODO: one sentence on what the system does for a buffet restaurant — ordering, tables, billing, or all three.', NULL,
     NULL, NULL, NULL, NULL, NULL,
     1, 1, 4, @now, @now)
ON DUPLICATE KEY UPDATE slug = slug;
SET @pid = (SELECT id FROM projects WHERE slug = 'buffet-system');

INSERT INTO case_studies
    (project_id, overview, context, problem, role, approach, architecture,
     database_notes, api_notes, security, deployment, outcome,
     features, challenges, decisions, updated_at)
VALUES
    (@pid, 'TODO: what the system is, who operates it, and in what kind of venue.', NULL, 'TODO: what the restaurant was doing before, and what broke at their scale.', 'TODO: which parts you built.',
     NULL, NULL, NULL, NULL,
     NULL, NULL, NULL,
     NULL, NULL, NULL, @now)
ON DUPLICATE KEY UPDATE project_id = project_id;

INSERT INTO projects
    (slug, title, category, description, summary, image, image_alt, year,
     live_url, github_url, featured, published, sort_order, created_at, updated_at)
VALUES
    ('portfolio', 'Portfolio', 'Web Development', 'This site — a server-rendered Nuxt 4 frontend with a Go API and MySQL behind it, containerised and deployed behind Nginx and Cloudflare.', 'This site is the smallest honest example of the stack I work in: a server-rendered Nuxt 4 frontend, a Go API handling the one route that genuinely needs a server, MySQL for the data that must persist, and a container setup that runs the same way locally and in production.',
     NULL, NULL, NULL, NULL, NULL,
     1, 1, 5, @now, @now)
ON DUPLICATE KEY UPDATE slug = slug;
SET @pid = (SELECT id FROM projects WHERE slug = 'portfolio');
INSERT INTO project_technologies (project_id, name, sort_order) VALUES (@pid, 'Nuxt 4', 0) ON DUPLICATE KEY UPDATE sort_order = VALUES(sort_order);
INSERT INTO project_technologies (project_id, name, sort_order) VALUES (@pid, 'Vue 3', 1) ON DUPLICATE KEY UPDATE sort_order = VALUES(sort_order);
INSERT INTO project_technologies (project_id, name, sort_order) VALUES (@pid, 'TypeScript', 2) ON DUPLICATE KEY UPDATE sort_order = VALUES(sort_order);
INSERT INTO project_technologies (project_id, name, sort_order) VALUES (@pid, 'Tailwind CSS', 3) ON DUPLICATE KEY UPDATE sort_order = VALUES(sort_order);
INSERT INTO project_technologies (project_id, name, sort_order) VALUES (@pid, 'Go', 4) ON DUPLICATE KEY UPDATE sort_order = VALUES(sort_order);
INSERT INTO project_technologies (project_id, name, sort_order) VALUES (@pid, 'MySQL', 5) ON DUPLICATE KEY UPDATE sort_order = VALUES(sort_order);
INSERT INTO project_technologies (project_id, name, sort_order) VALUES (@pid, 'Docker', 6) ON DUPLICATE KEY UPDATE sort_order = VALUES(sort_order);
INSERT INTO project_technologies (project_id, name, sort_order) VALUES (@pid, 'Nginx', 7) ON DUPLICATE KEY UPDATE sort_order = VALUES(sort_order);
INSERT INTO project_technologies (project_id, name, sort_order) VALUES (@pid, 'Cloudflare', 8) ON DUPLICATE KEY UPDATE sort_order = VALUES(sort_order);

INSERT INTO case_studies
    (project_id, overview, context, problem, role, approach, architecture,
     database_notes, api_notes, security, deployment, outcome,
     features, challenges, decisions, updated_at)
VALUES
    (@pid, 'A portfolio built as a production system rather than a static page, so the engineering choices on display are the ones actually running the site.', NULL, 'A portfolio has almost no inherent backend requirement. The interesting constraint is deciding where complexity is justified: adding a database and an API service for their own sake would contradict the judgement the site is meant to demonstrate.', 'Sole developer — design system, frontend, API, schema, containers, deployment documentation.',
     'Content lives in typed TypeScript modules and is prerendered, so pages ship as static HTML with no runtime data dependency. Only the contact form needs server behaviour, so that is the only thing with an API and a table behind it.', 'Cloudflare terminates TLS and fronts the origin. Nginx reverse-proxies to the Nuxt server, which prerenders every content route. The browser posts the contact form to a Nuxt server route, which forwards it server-side to the Go API — the API is never reachable from the public internet, so it needs no CORS surface. The Go service validates, rate-limits, and persists to MySQL.', 'One table, contact_messages, holding the submission plus request metadata for abuse investigation. Migrations are plain, numbered, forward-and-back SQL files — no ORM, because there is no schema complexity to justify one.', 'Go net/http with a small middleware chain: request ID, structured logging, panic recovery, body-size limit, security headers, and a per-IP token-bucket limiter. Two routes: POST /v1/contact and GET /health.',
     'The API binds to the container network only. Input is validated and length-bounded server-side before it reaches the database, statements are parameterised, error responses never echo internals, and secrets come from the environment rather than the image.', 'docker compose builds both services against a MySQL container with a persistent volume and health-gated startup ordering. The same compose file plus an env file is what runs in production behind Nginx.', 'The site is fully prerendered, keyboard accessible, and works with JavaScript-driven animation disabled. Build, typecheck, lint, and the API test suite all run clean.',
     '["Prerendered content routes with typed content modules","Dark, light, and system theme with persisted preference","Per-project case-study pages that render only verified sections","Contact API with validation, per-IP rate limiting, and honeypot spam protection","Person, WebSite, and CreativeWork structured data","Generated sitemap and robots.txt","Multi-stage Docker builds for both services with health checks"]', NULL, '[{"decision":"Prerender content routes instead of serving them from the database","rationale":"The content changes when I change it, not per request. Prerendering removes the database from the critical path for every page a visitor actually reads, so the site stays up and fast even if the API is down."},{"decision":"Proxy the contact form through the Nuxt server rather than calling Go from the browser","rationale":"It keeps the Go service unreachable from the internet and removes the need for a public CORS policy. The cost is one extra internal hop on a route that runs a few times a day."},{"decision":"No CMS or admin panel","rationale":"One author editing typed files gets type safety and version history for free. An admin panel would add authentication, sessions, and an attack surface to solve a problem that does not exist yet."}]', @now)
ON DUPLICATE KEY UPDATE project_id = project_id;

INSERT INTO projects
    (slug, title, category, description, summary, image, image_alt, year,
     live_url, github_url, featured, published, sort_order, created_at, updated_at)
VALUES
    ('wordpress-seo', 'WordPress & SEO', 'Web / SEO', 'TODO: one sentence on the kind of WordPress and SEO work you deliver, without naming clients you cannot cite.', NULL,
     NULL, NULL, NULL, NULL, NULL,
     1, 1, 6, @now, @now)
ON DUPLICATE KEY UPDATE slug = slug;
SET @pid = (SELECT id FROM projects WHERE slug = 'wordpress-seo');
INSERT INTO project_technologies (project_id, name, sort_order) VALUES (@pid, 'WordPress', 0) ON DUPLICATE KEY UPDATE sort_order = VALUES(sort_order);
INSERT INTO project_technologies (project_id, name, sort_order) VALUES (@pid, 'Elementor Pro', 1) ON DUPLICATE KEY UPDATE sort_order = VALUES(sort_order);
INSERT INTO project_technologies (project_id, name, sort_order) VALUES (@pid, 'PHP', 2) ON DUPLICATE KEY UPDATE sort_order = VALUES(sort_order);
INSERT INTO project_technologies (project_id, name, sort_order) VALUES (@pid, 'MySQL', 3) ON DUPLICATE KEY UPDATE sort_order = VALUES(sort_order);
INSERT INTO project_technologies (project_id, name, sort_order) VALUES (@pid, 'Technical SEO', 4) ON DUPLICATE KEY UPDATE sort_order = VALUES(sort_order);
INSERT INTO project_technologies (project_id, name, sort_order) VALUES (@pid, 'Structured Data', 5) ON DUPLICATE KEY UPDATE sort_order = VALUES(sort_order);
INSERT INTO project_technologies (project_id, name, sort_order) VALUES (@pid, 'Cloudflare', 6) ON DUPLICATE KEY UPDATE sort_order = VALUES(sort_order);
INSERT INTO project_technologies (project_id, name, sort_order) VALUES (@pid, 'cPanel', 7) ON DUPLICATE KEY UPDATE sort_order = VALUES(sort_order);

INSERT INTO case_studies
    (project_id, overview, context, problem, role, approach, architecture,
     database_notes, api_notes, security, deployment, outcome,
     features, challenges, decisions, updated_at)
VALUES
    (@pid, 'TODO: the scope of this work — build, migration, optimisation, or ongoing maintenance.', NULL, NULL, 'TODO: what you were responsible for.',
     'TODO: your technical SEO process — audit, fixes, measurement.', NULL, NULL, NULL,
     NULL, 'TODO: hosting, caching, and CDN configuration you set up.', NULL,
     NULL, NULL, NULL, @now)
ON DUPLICATE KEY UPDATE project_id = project_id;

-- ── Experience ─────────────────────────────────────────────────────────────
INSERT INTO experience_entries (label, title, description, sort_order) SELECT '2020', 'Started full-time software development', NULL, 0 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM experience_entries WHERE title = 'Started full-time software development');
INSERT INTO experience_entries (label, title, description, sort_order) SELECT 'Backend', 'Backend & API development', 'Business logic, REST APIs, authentication, validation, and third-party integrations.', 1 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM experience_entries WHERE title = 'Backend & API development');
INSERT INTO experience_entries (label, title, description, sort_order) SELECT 'Frontend', 'Frontend & web applications', 'API-driven interfaces, admin dashboards, and customer-facing web applications.', 2 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM experience_entries WHERE title = 'Frontend & web applications');
INSERT INTO experience_entries (label, title, description, sort_order) SELECT 'Mobile', 'Mobile applications', 'Cross-platform Flutter applications consuming the same backend services.', 3 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM experience_entries WHERE title = 'Mobile applications');
INSERT INTO experience_entries (label, title, description, sort_order) SELECT 'Data', 'Database & infrastructure', 'Relational schema design, migrations, query performance, Linux servers, and Nginx.', 4 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM experience_entries WHERE title = 'Database & infrastructure');
INSERT INTO experience_entries (label, title, description, sort_order) SELECT 'Production', 'Cloud, DevOps & production operations', 'Docker, Cloudflare, deployment pipelines, monitoring, backups, and ongoing maintenance.', 5 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM experience_entries WHERE title = 'Cloud, DevOps & production operations');
INSERT INTO experience_entries (label, title, description, sort_order) SELECT '2026', 'Full-Stack Software Developer', 'Owning systems end to end, from requirements through production maintenance.', 6 FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM experience_entries WHERE title = 'Full-Stack Software Developer');

-- ── Capabilities ───────────────────────────────────────────────────────────

INSERT INTO capabilities (slug, title, description, icon, items, sort_order)
VALUES (NULL, 'Software Architecture', 'System architecture, modular design, maintainable project structures, and scalable application design.', 'lucide:layout-template', '["System design","Modular structure","Domain separation","Code review","Documentation"]', 0)
ON DUPLICATE KEY UPDATE slug = slug;

INSERT INTO capabilities (slug, title, description, icon, items, sort_order)
VALUES (NULL, 'Backend & APIs', 'Business logic, REST APIs, authentication, authorization, validation, and third-party integrations.', 'lucide:server', '["Go","Laravel / PHP","REST","Auth & sessions","Validation","Integrations"]', 1)
ON DUPLICATE KEY UPDATE slug = slug;

INSERT INTO capabilities (slug, title, description, icon, items, sort_order)
VALUES (NULL, 'Frontend', 'Responsive, API-driven interfaces with a typed component architecture and measured performance.', 'lucide:monitor', '["Vue 3","Nuxt","TypeScript","Tailwind CSS","SSR / SSG","Accessibility"]', 2)
ON DUPLICATE KEY UPDATE slug = slug;

INSERT INTO capabilities (slug, title, description, icon, items, sort_order)
VALUES (NULL, 'Mobile', 'Cross-platform mobile applications sharing the same backend contracts as the web clients.', 'lucide:smartphone', '["Flutter","Android","iOS","Firebase","Mobile API integration","Release builds"]', 3)
ON DUPLICATE KEY UPDATE slug = slug;

INSERT INTO capabilities (slug, title, description, icon, items, sort_order)
VALUES (NULL, 'Data', 'Relational design that holds up under real data volume, with integrity and recovery planned in.', 'lucide:database', '["MySQL","Schema design","Migrations","Indexing","Query optimisation","Backup & recovery"]', 4)
ON DUPLICATE KEY UPDATE slug = slug;

INSERT INTO capabilities (slug, title, description, icon, items, sort_order)
VALUES (NULL, 'Infrastructure', 'Provisioning, serving, and routing production applications on Linux and managed platforms.', 'lucide:cloud', '["Linux / Ubuntu","Docker","Nginx","VPS","Railway","DigitalOcean","Cloudflare","cPanel"]', 5)
ON DUPLICATE KEY UPDATE slug = slug;

INSERT INTO capabilities (slug, title, description, icon, items, sort_order)
VALUES (NULL, 'Security', 'Application and infrastructure hardening treated as part of the build, not a later pass.', 'lucide:shield-check', '["Authentication","Authorization","Input validation","HTTPS / TLS","API protection","Rate limiting","Secure configuration"]', 6)
ON DUPLICATE KEY UPDATE slug = slug;

INSERT INTO capabilities (slug, title, description, icon, items, sort_order)
VALUES (NULL, 'Production', 'Keeping systems observable and recoverable once real users depend on them.', 'lucide:activity', '["Logging","Monitoring","Health checks","Error handling","Backups","Deployment","Maintenance"]', 7)
ON DUPLICATE KEY UPDATE slug = slug;

-- ── Services ───────────────────────────────────────────────────────────────

INSERT INTO services (slug, title, description, icon, sort_order)
VALUES (NULL, 'Custom Web Applications', 'Business systems, dashboards, portals, customer applications, and internal tools built around your actual workflow.', 'lucide:app-window', 0)
ON DUPLICATE KEY UPDATE slug = slug;

INSERT INTO services (slug, title, description, icon, sort_order)
VALUES (NULL, 'Backend & API Systems', 'Secure APIs, business logic, integrations, authentication, and the database design underneath them.', 'lucide:server-cog', 1)
ON DUPLICATE KEY UPDATE slug = slug;

INSERT INTO services (slug, title, description, icon, sort_order)
VALUES (NULL, 'Mobile Applications', 'Cross-platform mobile applications using Flutter, sharing one backend with your web product.', 'lucide:smartphone', 2)
ON DUPLICATE KEY UPDATE slug = slug;

INSERT INTO services (slug, title, description, icon, sort_order)
VALUES (NULL, 'E-commerce', 'Product catalogues, customer accounts, orders, payments, promotions, and the administration system that runs them.', 'lucide:shopping-bag', 3)
ON DUPLICATE KEY UPDATE slug = slug;

INSERT INTO services (slug, title, description, icon, sort_order)
VALUES (NULL, 'WordPress & SEO', 'Professional websites with Elementor, plus technical SEO, performance optimisation, and hosting setup.', 'lucide:search', 4)
ON DUPLICATE KEY UPDATE slug = slug;

INSERT INTO services (slug, title, description, icon, sort_order)
VALUES (NULL, 'Production Deployment', 'Docker, Linux, VPS, Nginx, Cloudflare, backups, monitoring, and the operational work after launch.', 'lucide:rocket', 5)
ON DUPLICATE KEY UPDATE slug = slug;

-- ── Principles ─────────────────────────────────────────────────────────────

INSERT INTO principles (slug, title, description, icon, sort_order)
VALUES ('architecture', 'Architecture', 'Designed before implementation, so the structure survives the second and third feature.', 'lucide:compass', 0)
ON DUPLICATE KEY UPDATE slug = slug;

INSERT INTO principles (slug, title, description, icon, sort_order)
VALUES ('security', 'Security', 'Considered from the application layer down to the infrastructure it runs on.', 'lucide:lock', 1)
ON DUPLICATE KEY UPDATE slug = slug;

INSERT INTO principles (slug, title, description, icon, sort_order)
VALUES ('reliability', 'Reliability', 'Errors, backups, monitoring, and recovery are part of the system, not an afterthought.', 'lucide:heart-pulse', 2)
ON DUPLICATE KEY UPDATE slug = slug;

INSERT INTO principles (slug, title, description, icon, sort_order)
VALUES ('maintainability', 'Maintainability', 'Clean structure and documentation so future development does not start with archaeology.', 'lucide:wrench', 3)
ON DUPLICATE KEY UPDATE slug = slug;

-- ── Positioning pillars ────────────────────────────────────────────────────

INSERT INTO pillars (slug, title, description, sort_order)
VALUES ('experience', 'Experience', 'Professional full-time software development since 2020.', 0)
ON DUPLICATE KEY UPDATE slug = slug;

INSERT INTO pillars (slug, title, description, sort_order)
VALUES ('technical-breadth', 'Technical breadth', 'Backend, frontend, mobile, databases, APIs, infrastructure, WordPress, SEO, and cloud deployment.', 1)
ON DUPLICATE KEY UPDATE slug = slug;

INSERT INTO pillars (slug, title, description, sort_order)
VALUES ('production-ownership', 'Production ownership', 'Architecture, development, database, security, deployment, monitoring, backup, and maintenance — not just writing code.', 2)
ON DUPLICATE KEY UPDATE slug = slug;

-- ── Site settings ──────────────────────────────────────────────────────────
INSERT INTO site_settings (setting_key, setting_value, updated_at) VALUES ('name', 'Kong Chansila', @now) ON DUPLICATE KEY UPDATE setting_key = setting_key;
INSERT INTO site_settings (setting_key, setting_value, updated_at) VALUES ('role', 'Full-Stack Software Developer', @now) ON DUPLICATE KEY UPDATE setting_key = setting_key;
INSERT INTO site_settings (setting_key, setting_value, updated_at) VALUES ('tagline', 'Designing, building, and operating production-ready web, mobile, and business systems since 2020.', @now) ON DUPLICATE KEY UPDATE setting_key = setting_key;
INSERT INTO site_settings (setting_key, setting_value, updated_at) VALUES ('headline', 'Building production-ready software', @now) ON DUPLICATE KEY UPDATE setting_key = setting_key;
INSERT INTO site_settings (setting_key, setting_value, updated_at) VALUES ('headline_tail', 'from architecture to deployment.', @now) ON DUPLICATE KEY UPDATE setting_key = setting_key;
INSERT INTO site_settings (setting_key, setting_value, updated_at) VALUES ('positioning', 'I build complete software systems across backend, frontend, mobile, databases, APIs, infrastructure, security, deployment, and production operations.', @now) ON DUPLICATE KEY UPDATE setting_key = setting_key;
INSERT INTO site_settings (setting_key, setting_value, updated_at) VALUES ('description', 'Full-Stack Software Developer building production-ready web, mobile, and business systems — backend, frontend, mobile, databases, APIs, infrastructure, and deployment. Full-time development since 2020.', @now) ON DUPLICATE KEY UPDATE setting_key = setting_key;
INSERT INTO site_settings (setting_key, setting_value, updated_at) VALUES ('start_year', '2020', @now) ON DUPLICATE KEY UPDATE setting_key = setting_key;
INSERT INTO site_settings (setting_key, setting_value, updated_at) VALUES ('location', 'Cambodia', @now) ON DUPLICATE KEY UPDATE setting_key = setting_key;
INSERT INTO site_settings (setting_key, setting_value, updated_at) VALUES ('email', 'membertsd@gmail.com', @now) ON DUPLICATE KEY UPDATE setting_key = setting_key;
INSERT INTO site_settings (setting_key, setting_value, updated_at) VALUES ('phone', NULL, @now) ON DUPLICATE KEY UPDATE setting_key = setting_key;
INSERT INTO site_settings (setting_key, setting_value, updated_at) VALUES ('availability', NULL, @now) ON DUPLICATE KEY UPDATE setting_key = setting_key;
INSERT INTO site_settings (setting_key, setting_value, updated_at) VALUES ('portrait', NULL, @now) ON DUPLICATE KEY UPDATE setting_key = setting_key;
INSERT INTO site_settings (setting_key, setting_value, updated_at) VALUES ('portrait_alt', 'Kong Chansila, Full-Stack Software Developer', @now) ON DUPLICATE KEY UPDATE setting_key = setting_key;
INSERT INTO site_settings (setting_key, setting_value, updated_at) VALUES ('resume_file', NULL, @now) ON DUPLICATE KEY UPDATE setting_key = setting_key;
INSERT INTO site_settings (setting_key, setting_value, updated_at) VALUES ('hero_stack', '["Go","Laravel","Vue","Nuxt","Flutter","MySQL","Docker","Cloudflare"]', @now) ON DUPLICATE KEY UPDATE setting_key = setting_key;
INSERT INTO site_settings (setting_key, setting_value, updated_at) VALUES ('profiles', '[]', @now) ON DUPLICATE KEY UPDATE setting_key = setting_key;
INSERT INTO site_settings (setting_key, setting_value, updated_at) VALUES ('about_paragraphs', '["I am a full-stack software developer with professional development experience since 2020. I work across backend systems, frontend applications, mobile development, databases, APIs, infrastructure, deployment, and production operations.","Most of my work has been building and running complete systems rather than isolated features: designing the data model, writing the API, building the interface that consumes it, then deploying and maintaining the result. That shapes how I make decisions — I favour structures that stay readable a year later, and I plan for the failure modes before they reach production."]', @now) ON DUPLICATE KEY UPDATE setting_key = setting_key;
INSERT INTO site_settings (setting_key, setting_value, updated_at) VALUES ('wordpress_seo_stack', '["WordPress","Elementor","Elementor Pro","PHP","MySQL","Technical SEO","On-page SEO","Performance","Mobile SEO","Sitemap","Structured Data","Cloudflare","cPanel"]', @now) ON DUPLICATE KEY UPDATE setting_key = setting_key;
INSERT INTO site_settings (setting_key, setting_value, updated_at) VALUES ('contact_enabled', 'true', @now) ON DUPLICATE KEY UPDATE setting_key = setting_key;
