/**
 * Generates backend/migrations/0003_seed_content.up.sql from the bundled
 * content modules.
 *
 * The content now lives in MySQL, but these files remain the source of the
 * initial data and the runtime fallback (see composables/useSiteContent.ts).
 * Generating the seed rather than hand-writing it means the two can never
 * disagree about what the site started with.
 *
 *   node scripts/export-seed.mjs
 *
 * Node's native TypeScript stripping imports the .ts modules directly, so there
 * is no build step.
 */
import { writeFile } from 'node:fs/promises'
import { registerHooks } from 'node:module'
import { resolve } from 'node:path'

// The content modules import each other without a file extension, which Vite
// resolves and plain Node does not. This hook closes that gap so the files stay
// idiomatic for the app rather than being contorted for this script.
registerHooks({
  resolve(specifier, context, nextResolve) {
    if (specifier.startsWith('.') && !/\.[cm]?[jt]s$/.test(specifier)) {
      try {
        return nextResolve(`${specifier}.ts`, context)
      } catch {
        // fall through to the default resolution below
      }
    }
    return nextResolve(specifier, context)
  },
})

const { projects } = await import('../content/projects.ts')
const { timeline, aboutParagraphs } = await import('../content/experience.ts')
const { capabilities, wordpressSeoStack } = await import('../content/capabilities.ts')
const { services } = await import('../content/services.ts')
const { siteConfig } = await import('../content/site.ts')

/** MySQL string literal, or NULL. */
function q(value) {
  if (value === undefined || value === null || value === '') return 'NULL'
  const escaped = String(value)
    .replaceAll('\\', '\\\\')
    .replaceAll("'", "\\'")
    .replaceAll('\n', '\\n')
    .replaceAll('\r', '')
  return `'${escaped}'`
}

/** JSON column literal, or NULL for an absent list. */
function json(value) {
  if (value === undefined || value === null) return 'NULL'
  return q(JSON.stringify(value))
}

const bool = (v) => (v ? 1 : 0)
const lines = []
const say = (s = '') => lines.push(s)

say('-- Seed content, generated by frontend/scripts/export-seed.mjs — do not edit by hand.')
say('-- Regenerate with: cd frontend && node scripts/export-seed.mjs')
say('--')
say('-- Every INSERT is idempotent, so applying this twice is harmless and it can')
say('-- be re-run against a database that already holds some of these rows.')
say()
say('SET @now = UTC_TIMESTAMP();')
say()

// ── Projects ────────────────────────────────────────────────────────────────
say('-- ── Projects ───────────────────────────────────────────────────────────────')
for (const p of projects) {
  say(`
INSERT INTO projects
    (slug, title, category, description, summary, image, image_alt, year,
     live_url, github_url, featured, published, sort_order, created_at, updated_at)
VALUES
    (${q(p.slug)}, ${q(p.title)}, ${q(p.category)}, ${q(p.description)}, ${q(p.summary)},
     ${q(p.image)}, ${q(p.imageAlt)}, ${q(p.year)}, ${q(p.liveUrl)}, ${q(p.githubUrl)},
     ${bool(p.featured)}, 1, ${p.order ?? 99}, @now, @now)
ON DUPLICATE KEY UPDATE slug = slug;`)

  say(`SET @pid = (SELECT id FROM projects WHERE slug = ${q(p.slug)});`)

  p.technologies.forEach((tech, i) => {
    say(
      `INSERT INTO project_technologies (project_id, name, sort_order) VALUES (@pid, ${q(tech)}, ${i}) ` +
        `ON DUPLICATE KEY UPDATE sort_order = VALUES(sort_order);`,
    )
  })

  const cs = p.caseStudy
  if (cs) {
    say(`
INSERT INTO case_studies
    (project_id, overview, context, problem, role, approach, architecture,
     database_notes, api_notes, security, deployment, outcome,
     features, challenges, decisions, updated_at)
VALUES
    (@pid, ${q(cs.overview)}, ${q(cs.context)}, ${q(cs.problem)}, ${q(cs.role)},
     ${q(cs.approach)}, ${q(cs.architecture)}, ${q(cs.database)}, ${q(cs.api)},
     ${q(cs.security)}, ${q(cs.deployment)}, ${q(cs.outcome)},
     ${json(cs.features)}, ${json(cs.challenges)}, ${json(cs.decisions)}, @now)
ON DUPLICATE KEY UPDATE project_id = project_id;`)
  }
}

// ── Experience ──────────────────────────────────────────────────────────────
say()
say('-- ── Experience ─────────────────────────────────────────────────────────────')
timeline.forEach((entry, i) => {
  say(
    `INSERT INTO experience_entries (label, title, description, sort_order) ` +
      `SELECT ${q(entry.label)}, ${q(entry.title)}, ${q(entry.description)}, ${i} ` +
      `FROM DUAL WHERE NOT EXISTS (SELECT 1 FROM experience_entries WHERE title = ${q(entry.title)});`,
  )
})

// ── Capabilities ────────────────────────────────────────────────────────────
say()
say('-- ── Capabilities ───────────────────────────────────────────────────────────')
capabilities.forEach((c, i) => {
  say(`
INSERT INTO capabilities (slug, title, description, icon, items, sort_order)
VALUES (${q(c.slug)}, ${q(c.title)}, ${q(c.description)}, ${q(c.icon)}, ${json(c.items)}, ${i})
ON DUPLICATE KEY UPDATE slug = slug;`)
})

// ── Services ────────────────────────────────────────────────────────────────
say()
say('-- ── Services ───────────────────────────────────────────────────────────────')
services.forEach((s, i) => {
  say(`
INSERT INTO services (slug, title, description, icon, sort_order)
VALUES (${q(s.slug)}, ${q(s.title)}, ${q(s.description)}, ${q(s.icon)}, ${i})
ON DUPLICATE KEY UPDATE slug = slug;`)
})

// ── Principles and positioning pillars ──────────────────────────────────────
// Not seeded here. Their tables are created by migrations 0006 and 0007, which
// run after this file, and those migrations insert the same rows themselves.
// Inserting them from 0003 failed every fresh install on a missing table.

// ── Settings ────────────────────────────────────────────────────────────────
say()
say('-- ── Site settings ──────────────────────────────────────────────────────────')
const settings = {
  'name': siteConfig.name,
  'role': siteConfig.role,
  'tagline': siteConfig.tagline,
  'headline': siteConfig.headline,
  'headline_tail': siteConfig.headlineTail,
  'positioning': siteConfig.positioning,
  'description': siteConfig.description,
  'start_year': String(siteConfig.startYear),
  'location': siteConfig.location,
  'email': siteConfig.email,
  'phone': siteConfig.phone,
  'availability': siteConfig.availability,
  'portrait': siteConfig.portrait,
  'portrait_alt': siteConfig.portraitAlt,
  'resume_file': siteConfig.resumeFile,
  'hero_stack': JSON.stringify(siteConfig.heroStack),
  'profiles': JSON.stringify(siteConfig.profiles),
  'about_paragraphs': JSON.stringify(aboutParagraphs),
  'wordpress_seo_stack': JSON.stringify(wordpressSeoStack),
  'contact_enabled': 'true',
}

for (const [key, value] of Object.entries(settings)) {
  say(
    `INSERT INTO site_settings (setting_key, setting_value, updated_at) ` +
      `VALUES (${q(key)}, ${q(value)}, @now) ON DUPLICATE KEY UPDATE setting_key = setting_key;`,
  )
}

say()

const out = resolve(import.meta.dirname, '../../backend/migrations/0003_seed_content.up.sql')
await writeFile(out, lines.join('\n'))

const down = resolve(import.meta.dirname, '../../backend/migrations/0003_seed_content.down.sql')
await writeFile(
  down,
  `-- Removes the seeded content. Destructive: anything edited in /admin since
-- seeding is deleted too. Take a backup first (scripts/backup-db.sh).
DELETE FROM site_settings;
DELETE FROM services;
DELETE FROM capabilities;
DELETE FROM experience_entries;
-- project_technologies and case_studies cascade from projects.
DELETE FROM projects;
`,
)

console.log(`seed written: ${out}`)
console.log(
  `  ${projects.length} projects · ${timeline.length} experience entries · ` +
    `${capabilities.length} capabilities · ${services.length} services · ` +
    `${Object.keys(settings).length} settings`,
)
